routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

/* Default Page */
Route::get('/', 'HomeController@index');

/* Home Page */
Route::get('/home', 'HomeController@index')->name('home');

/* Companies and Emplyees Routes */
Route::resource('companies', 'CompanyController');

Route::resource('employees', 'EmployeeController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    @include('layouts.head')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ trans('modules.logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="invisible">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/frame.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/bootstrap/css/bootstrap.min.css') }}">
    <!-- Font Awesome Icons -->
    <link href="{{ asset('bower_components/font-awesome.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="{{ asset('bower_components/ionicons.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/dist/css/skins/_all-skins.min.css') }}">
    <!-- Google Font -->
    <link rel="stylesheet" href="{{ asset('bower_components/css.css') }}">
    <!-- Datatable -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.css"/>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
  </head>

  <body class="hold-transition skin-blue sidebar-mini">

    <div class="wrapper">
      @include('layouts.header')
      @include('layouts.sidebar')
      <div class="content-wrapper">
        @yield('content')
      </div>

      <footer class="main-footer">
        <strong>Copyright &copy; 2014-2019 <a href="#">AdminLTE</a>.</strong> All rights reserved.
      </footer>
    </div>

    <!-- jQuery 3 -->
    <script src="{{ asset('bower_components/admin-lte/plugins/jQuery/jquery.min.js') }}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{ asset('bower_components/admin-lte/bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('bower_components/admin-lte/dist/js/adminlte.min.js') }}"></script>
    <!-- Datatable -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.js"></script>
    @yield('scripts')

  </body>

</html>

resources/views/layouts/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>{{ config('app.name', 'Laravel') }}</title>
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>
<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
<!-- Styles -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<!-- Font Awesome Icons -->
<link href="{{ asset('bower_components/font-awesome.min.css') }}" rel="stylesheet" type="text/css" />

<style>

.dataTable {
	border:solid 2px #333 !important;
}
.modal-content {
	border:2px solid #c0c0c0 !important;
}

.modal-login {
    color: #636363;
    width: 350px;
}
.modal-login .modal-content {
    padding: 20px;
    border-radius: 5px;
    border: none;
}
.modal-login .modal-header {
    border-bottom: none;
    position: relative;
    justify-content: center;
}
.modal-login h4 {
    text-align: center;
    font-size: 26px;
}
.modal-login  .form-group {
    position: relative;
}
.modal-login i {
    position: absolute;
    left: 13px;
    top: 11px;
    font-size: 18px;
}
.modal-login .form-control {
    padding-left: 40px;
}
.modal-login .form-control:focus {
    border-color: #00ce81;
}
.modal-login .form-control, .modal-login .btn {
    min-height: 40px;
    border-radius: 3px; 
}
.modal-login .hint-text {
    text-align: center;
    padding-top: 10px;
}
.modal-login .close {
    position: absolute;
    top: -5px;
    right: -5px;
}
.modal-login .btn, .modal-login .btn:active {   
    border: none;
    background: #00ce81 !important;
    line-height: normal;
}
.modal-login .btn:hover, .modal-login .btn:focus {
    background: #00bf78 !important;
}
.modal-login .modal-footer {
    background: #ecf0f1;
    border-color: #dee4e7;
    text-align: center;
    margin: 0 -20px -20px;
    border-radius: 5px;
    font-size: 13px;
    justify-content: center;
}
.modal-login .modal-footer a {
    color: #999;
}
.trigger-btn {
    display: inline-block;
    margin: 100px auto;
}

#myModal {
    display:block;
    padding-top: 50px;
}

.modal-lg {
	width: 400px !important;
}
</style>

resources/views/layouts/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="{{ route('home') }}" class="logo">
    <span class="logo-mini">HKB</span>
    <span class="logo-lg">{{ config('app.name', 'Laravel') }}</span>
  </a>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            
          </a>
          <ul class="dropdown-menu">
          </ul>
        </li>

        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-user nav-icon"></i>
            <span class="hidden-xs">{{ Auth::user()->name }}</span>
          </a>
          <ul class="dropdown-menu">

            <li class="user-header">
              <i class="fa fa-user nav-icon"></i>
              <p>
                {{ Auth::user()->name }}
              </p>
            </li>

            <li class="user-footer">
              <div class="pull-right">
                <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <button>{{ trans('modules.logout') }}</button>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
              </div>
            </li>

          </ul>
        </li>

      </ul>
    </div>
  </nav>
</header>
  

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left">
        <i class="fa fa-industry"></i>
      </div>
      <div class="pull-left info">
        <p>{{ Auth::user()->name }}</p>
      </div>
    </div>
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">{{ trans('modules.menu') }}</li>
      <li id="company">
        <a href="{{ route('companies.index') }}">
          <i class="fa fa-list-alt"></i> <span>{{ trans('modules.company.company_header') }}</span>
        </a>
      </li>
      <li id="employee">
        <a href="{{ route('employees.index') }}">
          <i class="fa fa-users"></i> <span>{{ trans('modules.employees.employee_header') }}
        </a>
      </li>
    </ul>
  </section>
</aside>